[theme]
# background = "black"
primary = "light white"
secondary = "light black"
title = "#6790EB"
playing = "#6790EB"
playing_selected = "dark blue"
# playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "#6790EB"
statusbar_bg = "#6790EB"
cmdline = "light white"
# cmdline_bg = "black"
search_match = "light red"

